Training model=base
{'config_format': 'markov', 'batch_size': 16, 'acc_steps': 1, 'seed': 0, 'device': device(type='cpu'), 'iterations': 500, 'lr': 0.002, 'warmup_percent': 0.02, 'weight_decay': 0.001, 'beta1': 0.9, 'beta2': 0.95, 'scheduler': 'cos', 'opt': 'adamw', 'eval_freq': 1, 'results_base_folder': './exps', 'grad_clip': 0.0, 'dataset': 'markov', 'vocab_size': 2, 'data_in_ram': False, 'model': 'base', 'use_pretrained': 'none', 'dropout': 0, 'n_head': 1, 'n_layer': 1, 'n_embd': 4, 'sequence_length': 1024, 'dtype': torch.float16, 'bias': False, 'no_compile': False, 'wandb': True, 'wandb_project': 'test', 'wandb_run_prefix': 'none', 'eval_seq_prefix': '0', 'distributed_backend': None, 'p': 0.2, 'q': 0.3, 'memory': -1, 'initial': 'steady', 'no_tying': False, 'init': 'base', 'v_std': 0, 'world_size': 1}
4293
Compiling model ...
tensor([1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0])
wte:
Parameter containing:
tensor([[-0.0195],
        [-0.0147],
        [ 0.0174],
        [-0.0099]], requires_grad=True)
wpe:
Parameter containing:
tensor([[-0.0236, -0.0158,  0.0179,  0.0233],
        [-0.0355,  0.0317,  0.0093,  0.0200],
        [-0.0093, -0.0081, -0.0317,  0.0171],
        ...,
        [ 0.0061,  0.0099, -0.0032,  0.0263],
        [-0.0299,  0.0128,  0.0123, -0.0016],
        [ 0.0099,  0.0038, -0.0092,  0.0096]], requires_grad=True)
W_Q W_K W_V:
[[-0.01436148  0.0278504  -0.04276938 -0.02421157]
 [-0.02846089 -0.02001207  0.01200863  0.01525253]
 [ 0.04494617  0.00553598  0.01993307  0.00733944]
 [ 0.03719916 -0.01008096  0.00830837  0.00637097]
 [ 0.04560659  0.02316407  0.0038307  -0.03537526]
 [ 0.01029514 -0.01017586  0.00728841 -0.03106816]
 [-0.00692317  0.01518096 -0.00098811  0.02983638]
 [-0.00097981 -0.03732094 -0.01296561 -0.0063504 ]
 [-0.01770131  0.00717245  0.00827647 -0.00946587]
 [ 0.00027376 -0.0105378   0.00929308 -0.01725982]
 [-0.00999919  0.00033454 -0.02497538  0.01022293]
 [ 0.01069679 -0.03023748 -0.00441913 -0.01085814]]
Approximation error:
tensor(8.6248e-05, grad_fn=<CompiledFunctionBackward>)
c_fc:
Parameter containing:
tensor([[-0.0253,  0.0091,  0.0090, -0.0167],
        [-0.0147, -0.0162, -0.0241,  0.0155],
        [ 0.0111,  0.0193, -0.0041,  0.0356],
        [-0.0117,  0.0187,  0.0046,  0.0317],
        [-0.0030,  0.0139,  0.0033,  0.0174],
        [-0.0089,  0.0055,  0.0242,  0.0034],
        [ 0.0307, -0.0019,  0.0224, -0.0369],
        [-0.0022,  0.0283,  0.0102,  0.0034],
        [ 0.0385, -0.0264, -0.0246,  0.0241],
        [-0.0535, -0.0206,  0.0090,  0.0069],
        [ 0.0009,  0.0065, -0.0385, -0.0336],
        [-0.0315, -0.0033, -0.0005,  0.0130],
        [-0.0278,  0.0434,  0.0202,  0.0442],
        [-0.0064,  0.0341, -0.0093,  0.0075],
        [ 0.0048,  0.0055, -0.0006, -0.0151],
        [-0.0099, -0.0119, -0.0262, -0.0176]], requires_grad=True)
c_proj:
Parameter containing:
tensor([[-0.0081, -0.0028,  0.0264,  0.0017, -0.0111,  0.0065, -0.0061,  0.0196,
          0.0033, -0.0007, -0.0057, -0.0250, -0.0209, -0.0108,  0.0112,  0.0010],
        [ 0.0054,  0.0169,  0.0050, -0.0072,  0.0241, -0.0125, -0.0119,  0.0035,
          0.0066,  0.0274, -0.0016,  0.0090, -0.0034,  0.0013,  0.0237,  0.0040],
        [-0.0190, -0.0182,  0.0017, -0.0007,  0.0057,  0.0120,  0.0183, -0.0050,
          0.0109, -0.0105,  0.0102,  0.0052,  0.0006, -0.0016,  0.0003, -0.0155],
        [-0.0087, -0.0009,  0.0188, -0.0301, -0.0062, -0.0094,  0.0098,  0.0040,
         -0.0091, -0.0017, -0.0086, -0.0107, -0.0031,  0.0114,  0.0136, -0.0066]],
       requires_grad=True)
Traceback (most recent call last):
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 1126, in wrap_numpy_ndarray
    value.flags.writeable = True
    ^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot set WRITEABLE flag to True of this array
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/main.py", line 153, in <module>
    main(args)
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/main.py", line 135, in main
    stats = train(model, opt, P, scheduler, args.iterations, args.acc_steps, args.batch_size, args.sequence_length, generator,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/optim/base.py", line 32, in train_base
    outputs = model(x, targets=y)
              ^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 281, in forward
    def forward(self, idx, targets=None, get_logits=False):
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 285, in torch_dynamo_resume_in_forward_at_285
    print(idx[0,:100])
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 293, in torch_dynamo_resume_in_forward_at_293
    print("wte:")
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 294, in torch_dynamo_resume_in_forward_at_294
    print(self.transformer.wte.weight)
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 295, in torch_dynamo_resume_in_forward_at_295
    print("wpe:")
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 315, in torch_dynamo_resume_in_forward_at_296
    x = block(x)
        ^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 169, in forward
    def forward(self, x):
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 171, in torch_dynamo_resume_in_forward_at_171
    y = self.attn(x)
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 173, in torch_dynamo_resume_in_forward_at_173
    print("Approximation error:")
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 174, in torch_dynamo_resume_in_forward_at_174
    print(torch.mean(torch.norm(y[0], dim=1) / torch.norm(z[0], dim=1)))
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 131, in forward
    def forward(self, x):
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 137, in torch_dynamo_resume_in_forward_at_137
    print("c_fc:")
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 138, in torch_dynamo_resume_in_forward_at_138
    print(self.c_fc.weight)
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 139, in torch_dynamo_resume_in_forward_at_139
    print("c_proj:")
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 140, in torch_dynamo_resume_in_forward_at_140
    print(self.c_proj.weight)
  File "/Users/bondasch/Downloads/IT/Markov/Markov-Simple/src/models/base.py", line 142, in torch_dynamo_resume_in_forward_at_142
    img_c_fc = plt.matshow(self.c_fc.weight.numpy(force=True))
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 400, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 390, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 1877, in log
    self._log(data=data, step=step, commit=commit)
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 1641, in _log
    self._partial_history_callback(data, step, commit)
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 1513, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/wandb/sdk/interface/interface.py", line 600, in publish_partial_history
    data = history_dict_to_json(run, data, step=user_step, ignore_copy_err=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/wandb/sdk/data_types/utils.py", line 52, in history_dict_to_json
    payload[key] = val_to_json(
                   ^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/wandb/sdk/data_types/utils.py", line 86, in val_to_json
    val = Plotly.make_plot_media(val)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/wandb/sdk/data_types/plotly.py", line 48, in make_plot_media
    return Image(val)
           ^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/wandb/sdk/data_types/image.py", line 179, in __init__
    self._initialize_from_data(data_or_path, mode, file_type)
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/wandb/sdk/data_types/image.py", line 302, in _initialize_from_data
    util.ensure_matplotlib_figure(data).savefig(buf, format="png")
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2187, in print_figure
    result = print_method(
             ^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
                                                                 ^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 497, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 445, in _print_pil
    FigureCanvasAgg.draw(self)
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/matplotlib/figure.py", line 3153, in draw
    self.patch.draw(renderer)
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/matplotlib/patches.py", line 588, in draw
    self._draw_paths_with_artist_properties(
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/matplotlib/patches.py", line 573, in _draw_paths_with_artist_properties
    renderer.draw_path(gc, *draw_path_args)
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 97, in draw_path
    nmax = mpl.rcParams['agg.path.chunksize']  # here at least for testing
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 921, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 786, in _convert_frame
    result = inner_convert(
             ^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
           ^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 676, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 535, in compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1036, in transform_code_object
    transformations(instructions, code_options)
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 500, in transform
    tracer.run()
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2149, in run
    super().run()
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 810, in run
    and self.step()
        ^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1311, in LOAD_ATTR
    result = BuiltinVariable(getattr).call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/variables/builtin.py", line 687, in call_function
    result = handler(tx, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/variables/builtin.py", line 1277, in call_getattr
    return obj.var_getattr(tx, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/variables/user_defined.py", line 746, in var_getattr
    ).call_function(tx, [], {})
      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 335, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 289, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 680, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2285, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2399, in inline_call_
    tracer.run()
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 810, in run
    and self.step()
        ^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1311, in LOAD_ATTR
    result = BuiltinVariable(getattr).call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/variables/builtin.py", line 687, in call_function
    result = handler(tx, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/variables/builtin.py", line 1277, in call_getattr
    return obj.var_getattr(tx, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/variables/user_defined.py", line 808, in var_getattr
    return VariableBuilder(tx, source)(subobj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 269, in __call__
    vt = self._wrap(value)
         ^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 402, in _wrap
    return type_dispatch(self, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 1130, in wrap_numpy_ndarray
    assert isinstance(value.base, np.nditer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError:
from user code:
   File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 98, in torch_dynamo_resume_in_draw_path_at_97
    npts = path.vertices.shape[0]
  File "/Users/bondasch/anaconda3/lib/python3.11/site-packages/matplotlib/path.py", line 214, in vertices
    return self._vertices
Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True